<?php

class HospitalityDetailsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('hospitality_details')->delete();
        
		\DB::table('hospitality_details')->insert(array (
			0 => 
			array (
				'id' => 76,
				'contact_id' => NULL,
				'venue_id' => 16,
				'airport_id' => NULL,
				'first_hotel_option_id' => 3,
				'first_hotel_distance_from_airport' => 99,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => 3,
				'second_hotel_distance_from_airport' => 90,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-02 15:56:47',
				'created_at' => '2014-10-02 15:34:23',
				'deleted_at' => NULL,
			),
			1 => 
			array (
				'id' => 77,
				'contact_id' => NULL,
				'venue_id' => 0,
				'airport_id' => NULL,
				'first_hotel_option_id' => 3,
				'first_hotel_distance_from_airport' => 11,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => 3,
				'second_hotel_distance_from_airport' => 11,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-02 15:38:21',
				'created_at' => '2014-10-02 15:38:21',
				'deleted_at' => NULL,
			),
			2 => 
			array (
				'id' => 78,
				'contact_id' => NULL,
				'venue_id' => 72,
				'airport_id' => NULL,
				'first_hotel_option_id' => 2,
				'first_hotel_distance_from_airport' => 1,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => 4,
				'second_hotel_distance_from_airport' => 2,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-02 15:55:41',
				'created_at' => '2014-10-02 15:55:41',
				'deleted_at' => NULL,
			),
			3 => 
			array (
				'id' => 79,
				'contact_id' => NULL,
				'venue_id' => 73,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-07 18:00:16',
				'created_at' => '2014-10-07 18:00:16',
				'deleted_at' => NULL,
			),
			4 => 
			array (
				'id' => 80,
				'contact_id' => NULL,
				'venue_id' => 74,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-10 11:58:28',
				'created_at' => '2014-10-10 11:58:28',
				'deleted_at' => NULL,
			),
			5 => 
			array (
				'id' => 81,
				'contact_id' => NULL,
				'venue_id' => 75,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-10 11:59:28',
				'created_at' => '2014-10-10 11:59:28',
				'deleted_at' => NULL,
			),
			6 => 
			array (
				'id' => 82,
				'contact_id' => NULL,
				'venue_id' => 76,
				'airport_id' => NULL,
				'first_hotel_option_id' => 5,
				'first_hotel_distance_from_airport' => 35,
				'first_hotel_distance_from_venue' => 10,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 25,
				'second_hotel_distance_from_venue' => 1,
				'updated_at' => '2014-11-14 13:40:50',
				'created_at' => '2014-10-17 13:51:34',
				'deleted_at' => NULL,
			),
			7 => 
			array (
				'id' => 83,
				'contact_id' => NULL,
				'venue_id' => 77,
				'airport_id' => NULL,
				'first_hotel_option_id' => 5,
				'first_hotel_distance_from_airport' => 15,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => 3,
				'second_hotel_distance_from_airport' => 20,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-11-19 12:36:53',
				'created_at' => '2014-10-20 14:58:44',
				'deleted_at' => NULL,
			),
			8 => 
			array (
				'id' => 84,
				'contact_id' => NULL,
				'venue_id' => 78,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-20 15:27:28',
				'created_at' => '2014-10-20 15:27:28',
				'deleted_at' => NULL,
			),
			9 => 
			array (
				'id' => 85,
				'contact_id' => NULL,
				'venue_id' => 79,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 2,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 20,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-20 16:08:25',
				'created_at' => '2014-10-20 16:04:51',
				'deleted_at' => NULL,
			),
			10 => 
			array (
				'id' => 86,
				'contact_id' => NULL,
				'venue_id' => 80,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 40,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 43,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-20 16:16:13',
				'created_at' => '2014-10-20 16:16:13',
				'deleted_at' => NULL,
			),
			11 => 
			array (
				'id' => 87,
				'contact_id' => NULL,
				'venue_id' => 81,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 45,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 45,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-20 16:26:24',
				'created_at' => '2014-10-20 16:26:24',
				'deleted_at' => NULL,
			),
			12 => 
			array (
				'id' => 88,
				'contact_id' => NULL,
				'venue_id' => 82,
				'airport_id' => NULL,
				'first_hotel_option_id' => 2,
				'first_hotel_distance_from_airport' => 12,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => 3,
				'second_hotel_distance_from_airport' => 232,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-21 09:24:53',
				'created_at' => '2014-10-21 09:24:53',
				'deleted_at' => NULL,
			),
			13 => 
			array (
				'id' => 89,
				'contact_id' => NULL,
				'venue_id' => 83,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 45,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-22 18:55:52',
				'created_at' => '2014-10-22 18:55:52',
				'deleted_at' => NULL,
			),
			14 => 
			array (
				'id' => 90,
				'contact_id' => NULL,
				'venue_id' => 84,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 15,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 15,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-22 19:11:15',
				'created_at' => '2014-10-22 19:11:15',
				'deleted_at' => NULL,
			),
			15 => 
			array (
				'id' => 91,
				'contact_id' => NULL,
				'venue_id' => 85,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 40,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 40,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-22 19:26:55',
				'created_at' => '2014-10-22 19:26:55',
				'deleted_at' => NULL,
			),
			16 => 
			array (
				'id' => 92,
				'contact_id' => NULL,
				'venue_id' => 86,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 1,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 55,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 09:52:32',
				'created_at' => '2014-10-23 09:52:32',
				'deleted_at' => NULL,
			),
			17 => 
			array (
				'id' => 93,
				'contact_id' => NULL,
				'venue_id' => 87,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 1,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 1,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 11:37:06',
				'created_at' => '2014-10-23 11:37:06',
				'deleted_at' => NULL,
			),
			18 => 
			array (
				'id' => 94,
				'contact_id' => NULL,
				'venue_id' => 88,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 15,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 20,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 11:48:25',
				'created_at' => '2014-10-23 11:48:25',
				'deleted_at' => NULL,
			),
			19 => 
			array (
				'id' => 95,
				'contact_id' => NULL,
				'venue_id' => 89,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 12,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 11,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 12:01:21',
				'created_at' => '2014-10-23 12:01:21',
				'deleted_at' => NULL,
			),
			20 => 
			array (
				'id' => 96,
				'contact_id' => NULL,
				'venue_id' => 90,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 11,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 10,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 12:20:57',
				'created_at' => '2014-10-23 12:20:57',
				'deleted_at' => NULL,
			),
			21 => 
			array (
				'id' => 97,
				'contact_id' => NULL,
				'venue_id' => 91,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 3,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 5,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 12:37:23',
				'created_at' => '2014-10-23 12:37:23',
				'deleted_at' => NULL,
			),
			22 => 
			array (
				'id' => 98,
				'contact_id' => NULL,
				'venue_id' => 92,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 30,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 12:48:00',
				'created_at' => '2014-10-23 12:48:00',
				'deleted_at' => NULL,
			),
			23 => 
			array (
				'id' => 99,
				'contact_id' => NULL,
				'venue_id' => 93,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 45,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 12:57:28',
				'created_at' => '2014-10-23 12:57:28',
				'deleted_at' => NULL,
			),
			24 => 
			array (
				'id' => 100,
				'contact_id' => NULL,
				'venue_id' => 94,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 13:08:23',
				'created_at' => '2014-10-23 13:08:23',
				'deleted_at' => NULL,
			),
			25 => 
			array (
				'id' => 101,
				'contact_id' => NULL,
				'venue_id' => 95,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 13:13:48',
				'created_at' => '2014-10-23 13:13:48',
				'deleted_at' => NULL,
			),
			26 => 
			array (
				'id' => 102,
				'contact_id' => NULL,
				'venue_id' => 96,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 20,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 20,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 13:21:43',
				'created_at' => '2014-10-23 13:21:43',
				'deleted_at' => NULL,
			),
			27 => 
			array (
				'id' => 103,
				'contact_id' => NULL,
				'venue_id' => 97,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-10-23 13:28:44',
				'created_at' => '2014-10-23 13:28:44',
				'deleted_at' => NULL,
			),
			28 => 
			array (
				'id' => 104,
				'contact_id' => NULL,
				'venue_id' => 98,
				'airport_id' => NULL,
				'first_hotel_option_id' => 3,
				'first_hotel_distance_from_airport' => 12,
				'first_hotel_distance_from_venue' => 13,
				'second_hotel_option_id' => 2,
				'second_hotel_distance_from_airport' => 12,
				'second_hotel_distance_from_venue' => 14,
				'updated_at' => '2014-10-24 09:52:55',
				'created_at' => '2014-10-24 09:21:57',
				'deleted_at' => NULL,
			),
			29 => 
			array (
				'id' => 105,
				'contact_id' => NULL,
				'venue_id' => 99,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 30,
				'first_hotel_distance_from_venue' => 5,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-11-06 16:39:36',
				'created_at' => '2014-11-06 16:39:36',
				'deleted_at' => NULL,
			),
			30 => 
			array (
				'id' => 106,
				'contact_id' => NULL,
				'venue_id' => 100,
				'airport_id' => NULL,
				'first_hotel_option_id' => 6,
				'first_hotel_distance_from_airport' => 30,
				'first_hotel_distance_from_venue' => 9,
				'second_hotel_option_id' => 8,
				'second_hotel_distance_from_airport' => 28,
				'second_hotel_distance_from_venue' => 6,
				'updated_at' => '2014-11-19 16:29:39',
				'created_at' => '2014-11-19 12:25:54',
				'deleted_at' => NULL,
			),
			31 => 
			array (
				'id' => 107,
				'contact_id' => NULL,
				'venue_id' => 101,
				'airport_id' => NULL,
				'first_hotel_option_id' => 10,
				'first_hotel_distance_from_airport' => 20,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => 11,
				'second_hotel_distance_from_airport' => 24,
				'second_hotel_distance_from_venue' => 5,
				'updated_at' => '2014-11-19 16:39:54',
				'created_at' => '2014-11-19 16:33:53',
				'deleted_at' => NULL,
			),
			32 => 
			array (
				'id' => 108,
				'contact_id' => NULL,
				'venue_id' => 102,
				'airport_id' => NULL,
				'first_hotel_option_id' => 12,
				'first_hotel_distance_from_airport' => 1512,
				'first_hotel_distance_from_venue' => 101,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-11-20 14:12:18',
				'created_at' => '2014-11-20 09:52:00',
				'deleted_at' => NULL,
			),
			33 => 
			array (
				'id' => 109,
				'contact_id' => NULL,
				'venue_id' => 103,
				'airport_id' => NULL,
				'first_hotel_option_id' => 14,
				'first_hotel_distance_from_airport' => 12,
				'first_hotel_distance_from_venue' => 19,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-11-24 17:29:33',
				'created_at' => '2014-11-24 17:16:41',
				'deleted_at' => NULL,
			),
			34 => 
			array (
				'id' => 110,
				'contact_id' => NULL,
				'venue_id' => 104,
				'airport_id' => NULL,
				'first_hotel_option_id' => 15,
				'first_hotel_distance_from_airport' => 20,
				'first_hotel_distance_from_venue' => 3,
				'second_hotel_option_id' => 16,
				'second_hotel_distance_from_airport' => 19,
				'second_hotel_distance_from_venue' => 4,
				'updated_at' => '2014-11-24 17:36:28',
				'created_at' => '2014-11-24 17:32:24',
				'deleted_at' => NULL,
			),
			35 => 
			array (
				'id' => 111,
				'contact_id' => NULL,
				'venue_id' => 105,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-11-24 17:56:18',
				'created_at' => '2014-11-24 17:55:36',
				'deleted_at' => NULL,
			),
			36 => 
			array (
				'id' => 112,
				'contact_id' => NULL,
				'venue_id' => 106,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-11-28 11:25:57',
				'created_at' => '2014-11-28 11:25:35',
				'deleted_at' => NULL,
			),
			37 => 
			array (
				'id' => 113,
				'contact_id' => NULL,
				'venue_id' => 107,
				'airport_id' => NULL,
				'first_hotel_option_id' => 19,
				'first_hotel_distance_from_airport' => 25,
				'first_hotel_distance_from_venue' => 11,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-01 17:24:14',
				'created_at' => '2014-12-01 17:16:34',
				'deleted_at' => NULL,
			),
			38 => 
			array (
				'id' => 114,
				'contact_id' => NULL,
				'venue_id' => 108,
				'airport_id' => NULL,
				'first_hotel_option_id' => 18,
				'first_hotel_distance_from_airport' => 25,
				'first_hotel_distance_from_venue' => 1,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-01 17:20:47',
				'created_at' => '2014-12-01 17:17:40',
				'deleted_at' => NULL,
			),
			39 => 
			array (
				'id' => 115,
				'contact_id' => NULL,
				'venue_id' => 109,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-10 16:28:50',
				'created_at' => '2014-12-10 16:25:59',
				'deleted_at' => NULL,
			),
			40 => 
			array (
				'id' => 116,
				'contact_id' => NULL,
				'venue_id' => 110,
				'airport_id' => NULL,
				'first_hotel_option_id' => 20,
				'first_hotel_distance_from_airport' => 5,
				'first_hotel_distance_from_venue' => 7,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-10 16:41:37',
				'created_at' => '2014-12-10 16:36:41',
				'deleted_at' => NULL,
			),
			41 => 
			array (
				'id' => 117,
				'contact_id' => NULL,
				'venue_id' => 111,
				'airport_id' => NULL,
				'first_hotel_option_id' => 21,
				'first_hotel_distance_from_airport' => 6,
				'first_hotel_distance_from_venue' => 11,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-10 16:58:15',
				'created_at' => '2014-12-10 16:54:47',
				'deleted_at' => NULL,
			),
			42 => 
			array (
				'id' => 118,
				'contact_id' => NULL,
				'venue_id' => 112,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-16 17:24:08',
				'created_at' => '2014-12-16 17:24:08',
				'deleted_at' => NULL,
			),
			43 => 
			array (
				'id' => 119,
				'contact_id' => NULL,
				'venue_id' => 113,
				'airport_id' => NULL,
				'first_hotel_option_id' => 23,
				'first_hotel_distance_from_airport' => 21,
				'first_hotel_distance_from_venue' => 8,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-16 17:38:26',
				'created_at' => '2014-12-16 17:32:08',
				'deleted_at' => NULL,
			),
			44 => 
			array (
				'id' => 120,
				'contact_id' => NULL,
				'venue_id' => 114,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-16 17:40:15',
				'created_at' => '2014-12-16 17:37:28',
				'deleted_at' => NULL,
			),
			45 => 
			array (
				'id' => 121,
				'contact_id' => NULL,
				'venue_id' => 115,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-16 17:45:50',
				'created_at' => '2014-12-16 17:44:43',
				'deleted_at' => NULL,
			),
			46 => 
			array (
				'id' => 122,
				'contact_id' => NULL,
				'venue_id' => 116,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-16 17:50:22',
				'created_at' => '2014-12-16 17:50:19',
				'deleted_at' => NULL,
			),
			47 => 
			array (
				'id' => 123,
				'contact_id' => NULL,
				'venue_id' => 117,
				'airport_id' => NULL,
				'first_hotel_option_id' => 24,
				'first_hotel_distance_from_airport' => 10,
				'first_hotel_distance_from_venue' => 6,
				'second_hotel_option_id' => 25,
				'second_hotel_distance_from_airport' => 5,
				'second_hotel_distance_from_venue' => 4,
				'updated_at' => '2014-12-16 17:57:34',
				'created_at' => '2014-12-16 17:53:09',
				'deleted_at' => NULL,
			),
			48 => 
			array (
				'id' => 124,
				'contact_id' => NULL,
				'venue_id' => 118,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-17 11:38:32',
				'created_at' => '2014-12-17 11:37:10',
				'deleted_at' => NULL,
			),
			49 => 
			array (
				'id' => 125,
				'contact_id' => NULL,
				'venue_id' => 119,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-17 11:42:55',
				'created_at' => '2014-12-17 11:42:52',
				'deleted_at' => NULL,
			),
			50 => 
			array (
				'id' => 126,
				'contact_id' => NULL,
				'venue_id' => 120,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 11:46:11',
				'created_at' => '2014-12-17 11:46:11',
				'deleted_at' => NULL,
			),
			51 => 
			array (
				'id' => 127,
				'contact_id' => NULL,
				'venue_id' => 121,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 11:48:42',
				'created_at' => '2014-12-17 11:48:42',
				'deleted_at' => NULL,
			),
			52 => 
			array (
				'id' => 128,
				'contact_id' => NULL,
				'venue_id' => 122,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 12:07:47',
				'created_at' => '2014-12-17 12:07:47',
				'deleted_at' => NULL,
			),
			53 => 
			array (
				'id' => 129,
				'contact_id' => NULL,
				'venue_id' => 123,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 12:48:26',
				'created_at' => '2014-12-17 12:48:26',
				'deleted_at' => NULL,
			),
			54 => 
			array (
				'id' => 130,
				'contact_id' => NULL,
				'venue_id' => 124,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 12:51:38',
				'created_at' => '2014-12-17 12:51:38',
				'deleted_at' => NULL,
			),
			55 => 
			array (
				'id' => 131,
				'contact_id' => NULL,
				'venue_id' => 125,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 12:54:42',
				'created_at' => '2014-12-17 12:54:42',
				'deleted_at' => NULL,
			),
			56 => 
			array (
				'id' => 132,
				'contact_id' => NULL,
				'venue_id' => 126,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 13:06:08',
				'created_at' => '2014-12-17 13:06:08',
				'deleted_at' => NULL,
			),
			57 => 
			array (
				'id' => 133,
				'contact_id' => NULL,
				'venue_id' => 127,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-17 14:41:31',
				'created_at' => '2014-12-17 14:41:21',
				'deleted_at' => NULL,
			),
			58 => 
			array (
				'id' => 134,
				'contact_id' => NULL,
				'venue_id' => 128,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-17 14:45:32',
				'created_at' => '2014-12-17 14:45:29',
				'deleted_at' => NULL,
			),
			59 => 
			array (
				'id' => 135,
				'contact_id' => NULL,
				'venue_id' => 129,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-17 14:59:07',
				'created_at' => '2014-12-17 14:59:04',
				'deleted_at' => NULL,
			),
			60 => 
			array (
				'id' => 136,
				'contact_id' => NULL,
				'venue_id' => 130,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:00:28',
				'created_at' => '2014-12-17 15:00:28',
				'deleted_at' => NULL,
			),
			61 => 
			array (
				'id' => 137,
				'contact_id' => NULL,
				'venue_id' => 131,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:02:56',
				'created_at' => '2014-12-17 15:02:56',
				'deleted_at' => NULL,
			),
			62 => 
			array (
				'id' => 138,
				'contact_id' => NULL,
				'venue_id' => 132,
				'airport_id' => NULL,
				'first_hotel_option_id' => 26,
				'first_hotel_distance_from_airport' => 15,
				'first_hotel_distance_from_venue' => 4,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-17 15:39:04',
				'created_at' => '2014-12-17 15:03:25',
				'deleted_at' => NULL,
			),
			63 => 
			array (
				'id' => 139,
				'contact_id' => NULL,
				'venue_id' => 133,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:04:20',
				'created_at' => '2014-12-17 15:04:20',
				'deleted_at' => NULL,
			),
			64 => 
			array (
				'id' => 140,
				'contact_id' => NULL,
				'venue_id' => 134,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:04:49',
				'created_at' => '2014-12-17 15:04:49',
				'deleted_at' => NULL,
			),
			65 => 
			array (
				'id' => 141,
				'contact_id' => NULL,
				'venue_id' => 135,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:05:39',
				'created_at' => '2014-12-17 15:05:39',
				'deleted_at' => NULL,
			),
			66 => 
			array (
				'id' => 142,
				'contact_id' => NULL,
				'venue_id' => 136,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:06:52',
				'created_at' => '2014-12-17 15:06:52',
				'deleted_at' => NULL,
			),
			67 => 
			array (
				'id' => 143,
				'contact_id' => NULL,
				'venue_id' => 137,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:07:23',
				'created_at' => '2014-12-17 15:07:23',
				'deleted_at' => NULL,
			),
			68 => 
			array (
				'id' => 144,
				'contact_id' => NULL,
				'venue_id' => 138,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:08:23',
				'created_at' => '2014-12-17 15:08:23',
				'deleted_at' => NULL,
			),
			69 => 
			array (
				'id' => 145,
				'contact_id' => NULL,
				'venue_id' => 139,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:08:55',
				'created_at' => '2014-12-17 15:08:55',
				'deleted_at' => NULL,
			),
			70 => 
			array (
				'id' => 146,
				'contact_id' => NULL,
				'venue_id' => 140,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:09:30',
				'created_at' => '2014-12-17 15:09:30',
				'deleted_at' => NULL,
			),
			71 => 
			array (
				'id' => 147,
				'contact_id' => NULL,
				'venue_id' => 141,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:10:20',
				'created_at' => '2014-12-17 15:10:20',
				'deleted_at' => NULL,
			),
			72 => 
			array (
				'id' => 148,
				'contact_id' => NULL,
				'venue_id' => 142,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:12:59',
				'created_at' => '2014-12-17 15:12:59',
				'deleted_at' => NULL,
			),
			73 => 
			array (
				'id' => 149,
				'contact_id' => NULL,
				'venue_id' => 143,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:14:33',
				'created_at' => '2014-12-17 15:14:33',
				'deleted_at' => NULL,
			),
			74 => 
			array (
				'id' => 150,
				'contact_id' => NULL,
				'venue_id' => 144,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:15:11',
				'created_at' => '2014-12-17 15:15:11',
				'deleted_at' => NULL,
			),
			75 => 
			array (
				'id' => 151,
				'contact_id' => NULL,
				'venue_id' => 145,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2014-12-17 15:16:14',
				'created_at' => '2014-12-17 15:16:14',
				'deleted_at' => NULL,
			),
			76 => 
			array (
				'id' => 152,
				'contact_id' => NULL,
				'venue_id' => 146,
				'airport_id' => NULL,
				'first_hotel_option_id' => 27,
				'first_hotel_distance_from_airport' => 33,
				'first_hotel_distance_from_venue' => 3,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-17 15:44:52',
				'created_at' => '2014-12-17 15:42:47',
				'deleted_at' => NULL,
			),
			77 => 
			array (
				'id' => 153,
				'contact_id' => NULL,
				'venue_id' => 147,
				'airport_id' => NULL,
				'first_hotel_option_id' => 28,
				'first_hotel_distance_from_airport' => 13,
				'first_hotel_distance_from_venue' => 1,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2014-12-17 16:33:50',
				'created_at' => '2014-12-17 16:32:24',
				'deleted_at' => NULL,
			),
			78 => 
			array (
				'id' => 154,
				'contact_id' => NULL,
				'venue_id' => 148,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-05 11:37:51',
				'created_at' => '2015-01-05 11:37:51',
				'deleted_at' => NULL,
			),
			79 => 
			array (
				'id' => 155,
				'contact_id' => NULL,
				'venue_id' => 149,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-05 11:49:05',
				'created_at' => '2015-01-05 11:49:05',
				'deleted_at' => NULL,
			),
			80 => 
			array (
				'id' => 156,
				'contact_id' => NULL,
				'venue_id' => 150,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2015-01-05 11:56:45',
				'created_at' => '2015-01-05 11:56:35',
				'deleted_at' => NULL,
			),
			81 => 
			array (
				'id' => 157,
				'contact_id' => NULL,
				'venue_id' => 151,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-08 13:06:51',
				'created_at' => '2015-01-08 13:06:51',
				'deleted_at' => NULL,
			),
			82 => 
			array (
				'id' => 158,
				'contact_id' => NULL,
				'venue_id' => 152,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-08 13:13:25',
				'created_at' => '2015-01-08 13:13:25',
				'deleted_at' => NULL,
			),
			83 => 
			array (
				'id' => 159,
				'contact_id' => NULL,
				'venue_id' => 153,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-08 13:17:03',
				'created_at' => '2015-01-08 13:17:03',
				'deleted_at' => NULL,
			),
			84 => 
			array (
				'id' => 160,
				'contact_id' => NULL,
				'venue_id' => 154,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-08 13:19:18',
				'created_at' => '2015-01-08 13:19:18',
				'deleted_at' => NULL,
			),
			85 => 
			array (
				'id' => 161,
				'contact_id' => NULL,
				'venue_id' => 155,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2015-01-08 13:40:08',
				'created_at' => '2015-01-08 13:37:34',
				'deleted_at' => NULL,
			),
			86 => 
			array (
				'id' => 162,
				'contact_id' => NULL,
				'venue_id' => 156,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-08 13:50:23',
				'created_at' => '2015-01-08 13:50:23',
				'deleted_at' => NULL,
			),
			87 => 
			array (
				'id' => 163,
				'contact_id' => NULL,
				'venue_id' => 157,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => 0,
				'first_hotel_distance_from_venue' => 0,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => 0,
				'second_hotel_distance_from_venue' => 0,
				'updated_at' => '2015-01-08 14:33:21',
				'created_at' => '2015-01-08 14:33:15',
				'deleted_at' => NULL,
			),
			88 => 
			array (
				'id' => 164,
				'contact_id' => NULL,
				'venue_id' => 158,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-08 14:37:14',
				'created_at' => '2015-01-08 14:37:14',
				'deleted_at' => NULL,
			),
			89 => 
			array (
				'id' => 165,
				'contact_id' => NULL,
				'venue_id' => 159,
				'airport_id' => NULL,
				'first_hotel_option_id' => NULL,
				'first_hotel_distance_from_airport' => NULL,
				'first_hotel_distance_from_venue' => NULL,
				'second_hotel_option_id' => NULL,
				'second_hotel_distance_from_airport' => NULL,
				'second_hotel_distance_from_venue' => NULL,
				'updated_at' => '2015-01-08 14:40:30',
				'created_at' => '2015-01-08 14:40:30',
				'deleted_at' => NULL,
			),
		));
	}

}
