<?php

class VenuesTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('venues')->delete();
        
		\DB::table('venues')->insert(array (
			0 => 
			array (
				'id' => 5,
				'main_contact_id' => NULL,
				'address_id' => 13,
				'name' => 'Melkweg',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-28 07:56:38',
				'created_at' => '0000-00-00 00:00:00',
				'deleted_at' => '2014-09-28 07:56:38',
			),
			1 => 
			array (
				'id' => 6,
				'main_contact_id' => NULL,
				'address_id' => 15,
				'name' => 'Paradiso',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => '',
				'capacity' => '9000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:08',
				'created_at' => '0000-00-00 00:00:00',
				'deleted_at' => '2014-10-02 11:08:08',
			),
			2 => 
			array (
				'id' => 8,
				'main_contact_id' => NULL,
				'address_id' => 19,
				'name' => 'xxx - xXx - xxx',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-29 08:24:22',
				'created_at' => '2014-09-26 08:59:18',
				'deleted_at' => '2014-09-29 08:24:22',
			),
			3 => 
			array (
				'id' => 9,
				'main_contact_id' => NULL,
				'address_id' => 50,
				'name' => 'asdad',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-29 08:24:12',
				'created_at' => '2014-09-28 10:27:58',
				'deleted_at' => '2014-09-29 08:24:12',
			),
			4 => 
			array (
				'id' => 10,
				'main_contact_id' => NULL,
				'address_id' => 51,
				'name' => 'asd235',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-29 08:24:09',
				'created_at' => '2014-09-28 10:30:31',
				'deleted_at' => '2014-09-29 08:24:09',
			),
			5 => 
			array (
				'id' => 11,
				'main_contact_id' => NULL,
				'address_id' => 52,
				'name' => 'asd2',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-29 08:24:07',
				'created_at' => '2014-09-28 10:33:48',
				'deleted_at' => '2014-09-29 08:24:07',
			),
			6 => 
			array (
				'id' => 12,
				'main_contact_id' => NULL,
				'address_id' => 53,
				'name' => 'sdfg',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-29 08:24:17',
				'created_at' => '2014-09-28 10:35:25',
				'deleted_at' => '2014-09-29 08:24:17',
			),
			7 => 
			array (
				'id' => 13,
				'main_contact_id' => NULL,
				'address_id' => 54,
				'name' => 'sdfsghdh',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-29 08:24:20',
				'created_at' => '2014-09-28 10:37:00',
				'deleted_at' => '2014-09-29 08:24:20',
			),
			8 => 
			array (
				'id' => 14,
				'main_contact_id' => NULL,
				'address_id' => 61,
				'name' => 'asdasdad',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-29 08:24:14',
				'created_at' => '2014-09-28 11:39:53',
				'deleted_at' => '2014-09-29 08:24:14',
			),
			9 => 
			array (
				'id' => 15,
				'main_contact_id' => NULL,
				'address_id' => 71,
				'name' => 'De Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'De Arena',
				'capacity' => '1000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 13:54:34',
				'created_at' => '2014-09-29 07:42:39',
				'deleted_at' => '2014-10-02 13:54:34',
			),
			10 => 
			array (
				'id' => 16,
				'main_contact_id' => NULL,
				'address_id' => 88,
				'name' => 'Alda Zone',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'blah',
				'capacity' => '7000',
				'dimension_height' => '8888',
				'dimension_width' => '8888',
				'dimension_length' => '8888',
				'rigging_capacity' => '',
				'notes' => 'bingo',
				'updated_at' => '2014-10-22 11:49:11',
				'created_at' => '2014-09-29 08:32:48',
				'deleted_at' => '2014-10-22 11:49:11',
			),
			11 => 
			array (
				'id' => 17,
				'main_contact_id' => NULL,
				'address_id' => 95,
				'name' => 'El cheapo',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:54',
				'created_at' => '2014-09-30 14:14:45',
				'deleted_at' => '2014-09-30 15:50:54',
			),
			12 => 
			array (
				'id' => 18,
				'main_contact_id' => NULL,
				'address_id' => 96,
				'name' => 'bammmmm',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:00',
				'created_at' => '2014-09-30 14:16:22',
				'deleted_at' => '2014-09-30 15:50:00',
			),
			13 => 
			array (
				'id' => 19,
				'main_contact_id' => NULL,
				'address_id' => 100,
				'name' => 'bammmmm',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:03',
				'created_at' => '2014-09-30 14:19:29',
				'deleted_at' => '2014-09-30 15:50:03',
			),
			14 => 
			array (
				'id' => 20,
				'main_contact_id' => NULL,
				'address_id' => 105,
				'name' => 'De Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:22',
				'created_at' => '2014-09-30 14:38:12',
				'deleted_at' => '2014-09-30 15:50:22',
			),
			15 => 
			array (
				'id' => 21,
				'main_contact_id' => NULL,
				'address_id' => 106,
				'name' => 'De Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:19',
				'created_at' => '2014-09-30 14:38:19',
				'deleted_at' => '2014-09-30 15:50:19',
			),
			16 => 
			array (
				'id' => 22,
				'main_contact_id' => NULL,
				'address_id' => 108,
				'name' => 'De Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:11',
				'created_at' => '2014-09-30 14:39:22',
				'deleted_at' => '2014-09-30 15:50:11',
			),
			17 => 
			array (
				'id' => 23,
				'main_contact_id' => NULL,
				'address_id' => 109,
				'name' => 'De Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:07',
				'created_at' => '2014-09-30 14:39:30',
				'deleted_at' => '2014-09-30 15:50:07',
			),
			18 => 
			array (
				'id' => 24,
				'main_contact_id' => NULL,
				'address_id' => 113,
				'name' => 'De Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:15',
				'created_at' => '2014-09-30 14:43:05',
				'deleted_at' => '2014-09-30 15:50:15',
			),
			19 => 
			array (
				'id' => 25,
				'main_contact_id' => NULL,
				'address_id' => 114,
				'name' => 'asd',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:38',
				'created_at' => '2014-09-30 14:44:10',
				'deleted_at' => '2014-09-30 15:49:38',
			),
			20 => 
			array (
				'id' => 26,
				'main_contact_id' => NULL,
				'address_id' => 115,
				'name' => 'assd',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:52',
				'created_at' => '2014-09-30 14:47:30',
				'deleted_at' => '2014-09-30 15:49:52',
			),
			21 => 
			array (
				'id' => 27,
				'main_contact_id' => NULL,
				'address_id' => 116,
				'name' => 'asdasdad',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:47',
				'created_at' => '2014-09-30 14:47:46',
				'deleted_at' => '2014-09-30 15:49:47',
			),
			22 => 
			array (
				'id' => 28,
				'main_contact_id' => NULL,
				'address_id' => 117,
				'name' => 'asdasdad',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:44',
				'created_at' => '2014-09-30 14:49:15',
				'deleted_at' => '2014-09-30 15:49:44',
			),
			23 => 
			array (
				'id' => 29,
				'main_contact_id' => NULL,
				'address_id' => 118,
				'name' => 'asdasdad',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:41',
				'created_at' => '2014-09-30 14:50:11',
				'deleted_at' => '2014-09-30 15:49:41',
			),
			24 => 
			array (
				'id' => 30,
				'main_contact_id' => NULL,
				'address_id' => 119,
				'name' => 'abc',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:29',
				'created_at' => '2014-09-30 14:53:40',
				'deleted_at' => '2014-09-30 15:49:29',
			),
			25 => 
			array (
				'id' => 31,
				'main_contact_id' => NULL,
				'address_id' => 125,
				'name' => 'whatever',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:31',
				'created_at' => '2014-09-30 14:57:27',
				'deleted_at' => '2014-09-30 15:50:31',
			),
			26 => 
			array (
				'id' => 32,
				'main_contact_id' => NULL,
				'address_id' => 139,
				'name' => 'pop',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:42',
				'created_at' => '2014-09-30 15:26:04',
				'deleted_at' => '2014-09-30 15:50:42',
			),
			27 => 
			array (
				'id' => 33,
				'main_contact_id' => NULL,
				'address_id' => 140,
				'name' => 'pop',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:40',
				'created_at' => '2014-09-30 15:26:12',
				'deleted_at' => '2014-09-30 15:50:40',
			),
			28 => 
			array (
				'id' => 34,
				'main_contact_id' => NULL,
				'address_id' => 141,
				'name' => 'asd',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:35',
				'created_at' => '2014-09-30 15:27:05',
				'deleted_at' => '2014-09-30 15:49:35',
			),
			29 => 
			array (
				'id' => 35,
				'main_contact_id' => NULL,
				'address_id' => 142,
				'name' => 'asdw',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:50',
				'created_at' => '2014-09-30 15:27:32',
				'deleted_at' => '2014-09-30 15:49:50',
			),
			30 => 
			array (
				'id' => 36,
				'main_contact_id' => NULL,
				'address_id' => 143,
				'name' => 'abcd',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:32',
				'created_at' => '2014-09-30 15:36:14',
				'deleted_at' => '2014-09-30 15:49:32',
			),
			31 => 
			array (
				'id' => 37,
				'main_contact_id' => NULL,
				'address_id' => 150,
				'name' => 'rock',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:37',
				'created_at' => '2014-09-30 15:38:18',
				'deleted_at' => '2014-09-30 15:50:37',
			),
			32 => 
			array (
				'id' => 38,
				'main_contact_id' => NULL,
				'address_id' => 151,
				'name' => 'eggs',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:50:28',
				'created_at' => '2014-09-30 15:39:21',
				'deleted_at' => '2014-09-30 15:50:28',
			),
			33 => 
			array (
				'id' => 39,
				'main_contact_id' => NULL,
				'address_id' => 153,
				'name' => 'bacon',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-09-30 15:49:57',
				'created_at' => '2014-09-30 15:39:48',
				'deleted_at' => '2014-09-30 15:49:57',
			),
			34 => 
			array (
				'id' => 40,
				'main_contact_id' => NULL,
				'address_id' => 159,
				'name' => 'Megadiso',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'mega',
				'capacity' => 'mega',
				'dimension_height' => '1',
				'dimension_width' => '1',
				'dimension_length' => '1',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:05',
				'created_at' => '2014-10-02 06:10:49',
				'deleted_at' => '2014-10-02 11:08:05',
			),
			35 => 
			array (
				'id' => 41,
				'main_contact_id' => NULL,
				'address_id' => 161,
				'name' => 'mega',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'hogwarts',
				'capacity' => '1',
				'dimension_height' => '1',
				'dimension_width' => '1',
				'dimension_length' => '1',
				'rigging_capacity' => '1',
				'notes' => '',
				'updated_at' => '2014-10-02 11:07:59',
				'created_at' => '2014-10-02 06:31:44',
				'deleted_at' => '2014-10-02 11:07:59',
			),
			36 => 
			array (
				'id' => 42,
				'main_contact_id' => NULL,
				'address_id' => 170,
				'name' => 'what',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'ppp',
				'capacity' => '12',
				'dimension_height' => '1',
				'dimension_width' => '1',
				'dimension_length' => '1',
				'rigging_capacity' => '111',
				'notes' => '',
				'updated_at' => '2014-10-02 11:07:56',
				'created_at' => '2014-10-02 07:16:44',
				'deleted_at' => '2014-10-02 11:07:56',
			),
			37 => 
			array (
				'id' => 43,
				'main_contact_id' => NULL,
				'address_id' => 238,
				'name' => 'le venue',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:24:24',
				'created_at' => '2014-10-02 08:21:43',
				'deleted_at' => '2014-10-02 08:24:24',
			),
			38 => 
			array (
				'id' => 44,
				'main_contact_id' => NULL,
				'address_id' => 239,
				'name' => 'le venue',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:24:27',
				'created_at' => '2014-10-02 08:21:48',
				'deleted_at' => '2014-10-02 08:24:27',
			),
			39 => 
			array (
				'id' => 45,
				'main_contact_id' => NULL,
				'address_id' => 240,
				'name' => 'le venue',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:24:30',
				'created_at' => '2014-10-02 08:21:49',
				'deleted_at' => '2014-10-02 08:24:30',
			),
			40 => 
			array (
				'id' => 46,
				'main_contact_id' => NULL,
				'address_id' => 241,
				'name' => 'le venue',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:24:32',
				'created_at' => '2014-10-02 08:21:50',
				'deleted_at' => '2014-10-02 08:24:32',
			),
			41 => 
			array (
				'id' => 47,
				'main_contact_id' => NULL,
				'address_id' => 242,
				'name' => 'le venue',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:14',
				'created_at' => '2014-10-02 08:21:51',
				'deleted_at' => '2014-10-02 11:08:14',
			),
			42 => 
			array (
				'id' => 48,
				'main_contact_id' => NULL,
				'address_id' => 243,
				'name' => 'jjj',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:21',
				'created_at' => '2014-10-02 08:26:15',
				'deleted_at' => '2014-10-02 11:08:21',
			),
			43 => 
			array (
				'id' => 49,
				'main_contact_id' => NULL,
				'address_id' => 245,
				'name' => 'asx',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:40:24',
				'created_at' => '2014-10-02 08:27:55',
				'deleted_at' => '2014-10-02 08:40:24',
			),
			44 => 
			array (
				'id' => 50,
				'main_contact_id' => NULL,
				'address_id' => 246,
				'name' => 'asx',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:40:18',
				'created_at' => '2014-10-02 08:28:01',
				'deleted_at' => '2014-10-02 08:40:18',
			),
			45 => 
			array (
				'id' => 51,
				'main_contact_id' => NULL,
				'address_id' => 255,
				'name' => 'blah',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:40:21',
				'created_at' => '2014-10-02 08:40:03',
				'deleted_at' => '2014-10-02 08:40:21',
			),
			46 => 
			array (
				'id' => 52,
				'main_contact_id' => NULL,
				'address_id' => 256,
				'name' => 'blah',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:40:31',
				'created_at' => '2014-10-02 08:40:05',
				'deleted_at' => '2014-10-02 08:40:31',
			),
			47 => 
			array (
				'id' => 53,
				'main_contact_id' => NULL,
				'address_id' => 257,
				'name' => 'blah',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:40:34',
				'created_at' => '2014-10-02 08:40:07',
				'deleted_at' => '2014-10-02 08:40:34',
			),
			48 => 
			array (
				'id' => 54,
				'main_contact_id' => NULL,
				'address_id' => 258,
				'name' => 'blah',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:40:28',
				'created_at' => '2014-10-02 08:40:08',
				'deleted_at' => '2014-10-02 08:40:28',
			),
			49 => 
			array (
				'id' => 55,
				'main_contact_id' => NULL,
				'address_id' => 259,
				'name' => 'blah',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:29',
				'created_at' => '2014-10-02 08:40:09',
				'deleted_at' => '2014-10-02 11:08:29',
			),
			50 => 
			array (
				'id' => 56,
				'main_contact_id' => NULL,
				'address_id' => 260,
				'name' => 'blah',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:40:37',
				'created_at' => '2014-10-02 08:40:10',
				'deleted_at' => '2014-10-02 08:40:37',
			),
			51 => 
			array (
				'id' => 57,
				'main_contact_id' => NULL,
				'address_id' => 268,
				'name' => 'jhg',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:49:54',
				'created_at' => '2014-10-02 08:42:31',
				'deleted_at' => '2014-10-02 08:49:54',
			),
			52 => 
			array (
				'id' => 58,
				'main_contact_id' => NULL,
				'address_id' => 269,
				'name' => 'jhg',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:49:57',
				'created_at' => '2014-10-02 08:42:34',
				'deleted_at' => '2014-10-02 08:49:57',
			),
			53 => 
			array (
				'id' => 59,
				'main_contact_id' => NULL,
				'address_id' => 270,
				'name' => 'jhg',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:50:00',
				'created_at' => '2014-10-02 08:42:37',
				'deleted_at' => '2014-10-02 08:50:00',
			),
			54 => 
			array (
				'id' => 60,
				'main_contact_id' => NULL,
				'address_id' => 271,
				'name' => 'jhg',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:50:02',
				'created_at' => '2014-10-02 08:42:40',
				'deleted_at' => '2014-10-02 08:50:02',
			),
			55 => 
			array (
				'id' => 61,
				'main_contact_id' => NULL,
				'address_id' => 272,
				'name' => 'jhg',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 08:50:05',
				'created_at' => '2014-10-02 08:42:42',
				'deleted_at' => '2014-10-02 08:50:05',
			),
			56 => 
			array (
				'id' => 62,
				'main_contact_id' => NULL,
				'address_id' => 273,
				'name' => 'aaa',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'aaa',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '100',
				'notes' => '',
				'updated_at' => '2014-10-02 09:54:35',
				'created_at' => '2014-10-02 08:50:17',
				'deleted_at' => '2014-10-02 09:54:35',
			),
			57 => 
			array (
				'id' => 63,
				'main_contact_id' => NULL,
				'address_id' => 275,
				'name' => 'mega venue',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:02',
				'created_at' => '2014-10-02 08:52:34',
				'deleted_at' => '2014-10-02 11:08:02',
			),
			58 => 
			array (
				'id' => 64,
				'main_contact_id' => NULL,
				'address_id' => 276,
				'name' => 'lalala',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:17',
				'created_at' => '2014-10-02 08:53:47',
				'deleted_at' => '2014-10-02 11:08:17',
			),
			59 => 
			array (
				'id' => 65,
				'main_contact_id' => NULL,
				'address_id' => 277,
				'name' => 'asdxcz',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:26',
				'created_at' => '2014-10-02 08:54:10',
				'deleted_at' => '2014-10-02 11:08:26',
			),
			60 => 
			array (
				'id' => 66,
				'main_contact_id' => NULL,
				'address_id' => 278,
				'name' => 'aas',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:24',
				'created_at' => '2014-10-02 08:54:33',
				'deleted_at' => '2014-10-02 11:08:24',
			),
			61 => 
			array (
				'id' => 67,
				'main_contact_id' => NULL,
				'address_id' => 279,
				'name' => 'a',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 09:54:32',
				'created_at' => '2014-10-02 09:44:36',
				'deleted_at' => '2014-10-02 09:54:32',
			),
			62 => 
			array (
				'id' => 68,
				'main_contact_id' => NULL,
				'address_id' => 280,
				'name' => 'a',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 09:54:29',
				'created_at' => '2014-10-02 09:46:40',
				'deleted_at' => '2014-10-02 09:54:29',
			),
			63 => 
			array (
				'id' => 69,
				'main_contact_id' => NULL,
				'address_id' => 281,
				'name' => 'a',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-02 09:54:26',
				'created_at' => '2014-10-02 09:46:51',
				'deleted_at' => '2014-10-02 09:54:26',
			),
			64 => 
			array (
				'id' => 70,
				'main_contact_id' => NULL,
				'address_id' => 282,
				'name' => 'le venue',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '1000',
				'notes' => '',
				'updated_at' => '2014-10-02 11:08:11',
				'created_at' => '2014-10-02 09:54:58',
				'deleted_at' => '2014-10-02 11:08:11',
			),
			65 => 
			array (
				'id' => 72,
				'main_contact_id' => NULL,
				'address_id' => 292,
				'name' => 'Eenvoud',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => 'simple hall',
				'capacity' => '500',
				'dimension_height' => '1',
				'dimension_width' => '1',
				'dimension_length' => '1',
				'rigging_capacity' => '200',
				'notes' => '',
				'updated_at' => '2014-10-22 11:56:27',
				'created_at' => '2014-10-02 13:55:41',
				'deleted_at' => '2014-10-22 11:56:27',
			),
			66 => 
			array (
				'id' => 73,
				'main_contact_id' => NULL,
				'address_id' => 294,
				'name' => 'asd',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-22 11:48:42',
				'created_at' => '2014-10-07 16:00:16',
				'deleted_at' => '2014-10-22 11:48:42',
			),
			67 => 
			array (
				'id' => 74,
				'main_contact_id' => NULL,
				'address_id' => 326,
				'name' => 'test',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '24500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '200',
				'notes' => '',
				'updated_at' => '2014-10-22 11:49:03',
				'created_at' => '2014-10-10 09:58:28',
				'deleted_at' => '2014-10-22 11:49:03',
			),
			68 => 
			array (
				'id' => 75,
				'main_contact_id' => NULL,
				'address_id' => 328,
				'name' => 'aeg',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-22 11:56:24',
				'created_at' => '2014-10-10 09:59:28',
				'deleted_at' => '2014-10-22 11:56:24',
			),
			69 => 
			array (
				'id' => 76,
				'main_contact_id' => NULL,
				'address_id' => 344,
			'name' => 'IEC (INTERNATIONAL EXHIBITION CENTER)',
				'indoor_or_outdoor' => '0',
			'name_of_hall' => 'IEC (INTERNATIONAL EXHIBITION CENTER)',
				'capacity' => '12000',
				'dimension_height' => '14,2',
				'dimension_width' => '90',
				'dimension_length' => '110',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-14 12:44:18',
				'created_at' => '2014-10-17 11:51:34',
				'deleted_at' => NULL,
			),
			70 => 
			array (
				'id' => 77,
				'main_contact_id' => NULL,
				'address_id' => 349,
				'name' => 'Arena Armeec',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Arena Armeec',
				'capacity' => '8000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '2000',
				'notes' => '',
				'updated_at' => '2014-10-22 14:52:47',
				'created_at' => '2014-10-20 12:58:44',
				'deleted_at' => NULL,
			),
			71 => 
			array (
				'id' => 78,
				'main_contact_id' => NULL,
				'address_id' => 354,
				'name' => 'SKK ARENA',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'SKK ARENA',
				'capacity' => '15000',
				'dimension_height' => '25',
				'dimension_width' => '80',
				'dimension_length' => '125',
				'rigging_capacity' => '50 TONNES',
				'notes' => '',
				'updated_at' => '2014-10-20 13:27:28',
				'created_at' => '2014-10-20 13:27:28',
				'deleted_at' => NULL,
			),
			72 => 
			array (
				'id' => 79,
				'main_contact_id' => NULL,
				'address_id' => 360,
				'name' => 'HELSINKI EXHIBITION & CONVENTION CENTRE',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'HALL NO.7',
				'capacity' => '7500',
				'dimension_height' => '14',
				'dimension_width' => '90',
				'dimension_length' => '120',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-04-20 13:35:56',
				'created_at' => '2014-10-20 14:04:51',
				'deleted_at' => '2015-04-20 13:35:56',
			),
			73 => 
			array (
				'id' => 80,
				'main_contact_id' => NULL,
				'address_id' => 361,
				'name' => 'MINSK ARENA',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'MINSK ARENA',
				'capacity' => '12000',
				'dimension_height' => '25',
				'dimension_width' => '35',
				'dimension_length' => '65',
				'rigging_capacity' => '60T',
				'notes' => '',
				'updated_at' => '2014-10-20 14:16:13',
				'created_at' => '2014-10-20 14:16:13',
				'deleted_at' => NULL,
			),
			74 => 
			array (
				'id' => 81,
				'main_contact_id' => NULL,
				'address_id' => 364,
				'name' => 'AUDITORIO BANAMEX',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '8000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '30T',
				'notes' => '',
				'updated_at' => '2014-10-20 14:26:24',
				'created_at' => '2014-10-20 14:26:24',
				'deleted_at' => NULL,
			),
			75 => 
			array (
				'id' => 82,
				'main_contact_id' => NULL,
				'address_id' => 367,
				'name' => 'TEST',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => 'name',
				'capacity' => '16000',
				'dimension_height' => '123',
				'dimension_width' => '123',
				'dimension_length' => '123',
				'rigging_capacity' => '500',
				'notes' => '1',
				'updated_at' => '2014-10-22 11:49:05',
				'created_at' => '2014-10-21 07:24:53',
				'deleted_at' => '2014-10-22 11:49:05',
			),
			76 => 
			array (
				'id' => 83,
				'main_contact_id' => NULL,
				'address_id' => 370,
				'name' => 'NEW TAIPEI CITY EXHIBITION CENTER',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '6500',
				'dimension_height' => '9-16M',
				'dimension_width' => '6000M',
				'dimension_length' => '6800M',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-22 16:55:52',
				'created_at' => '2014-10-22 16:55:52',
				'deleted_at' => NULL,
			),
			77 => 
			array (
				'id' => 84,
				'main_contact_id' => NULL,
				'address_id' => 377,
				'name' => 'BRISBANE ENTERTAINMENT CENTRE',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'MAIN ARENA',
				'capacity' => '10000',
				'dimension_height' => '16.5M',
				'dimension_width' => '43M',
				'dimension_length' => '67M',
				'rigging_capacity' => 'UP TO 90T.',
				'notes' => 'CAPACITY: 4900 FLOOR, 1450 LOWER CIRCLE, 3800 UPPER CIRCLE',
				'updated_at' => '2014-10-22 17:11:15',
				'created_at' => '2014-10-22 17:11:15',
				'deleted_at' => NULL,
			),
			78 => 
			array (
				'id' => 85,
				'main_contact_id' => NULL,
				'address_id' => 381,
				'name' => 'THE COCA-COLA DOME',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '18000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '19T ON EXISTING MOTHER GRID',
				'notes' => '',
				'updated_at' => '2014-10-22 17:26:55',
				'created_at' => '2014-10-22 17:26:55',
				'deleted_at' => NULL,
			),
			79 => 
			array (
				'id' => 86,
				'main_contact_id' => NULL,
				'address_id' => 391,
				'name' => 'SVP Stadium, NSCI ,Mumbai',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'FULL STADIUM ',
				'capacity' => '10000',
				'dimension_height' => '40FT',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-23 07:52:32',
				'created_at' => '2014-10-23 07:52:32',
				'deleted_at' => NULL,
			),
			80 => 
			array (
				'id' => 87,
				'main_contact_id' => NULL,
				'address_id' => 410,
				'name' => 'PALACIO DE LOS DEPORTES',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '21500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '60T',
				'notes' => '',
				'updated_at' => '2014-10-23 09:37:06',
				'created_at' => '2014-10-23 09:37:06',
				'deleted_at' => NULL,
			),
			81 => 
			array (
				'id' => 88,
				'main_contact_id' => NULL,
				'address_id' => 414,
				'name' => 'MOA ARENA',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'ARENA',
				'capacity' => '8000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-23 09:48:25',
				'created_at' => '2014-10-23 09:48:25',
				'deleted_at' => NULL,
			),
			82 => 
			array (
				'id' => 89,
				'main_contact_id' => NULL,
				'address_id' => 418,
				'name' => 'HISENSE ARENA',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'MAIN ARENA',
				'capacity' => '7500',
				'dimension_height' => '12M',
				'dimension_width' => '37.8M',
				'dimension_length' => '84M',
				'rigging_capacity' => '50T IN EACH HALF',
				'notes' => '',
				'updated_at' => '2014-10-23 10:01:21',
				'created_at' => '2014-10-23 10:01:21',
				'deleted_at' => NULL,
			),
			83 => 
			array (
				'id' => 90,
				'main_contact_id' => NULL,
				'address_id' => 420,
				'name' => 'SYDNEY SHOWGROUNDS',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'DOME & HALLS 2, 3 & 4',
				'capacity' => '17000',
				'dimension_height' => '18M',
				'dimension_width' => '67',
				'dimension_length' => '215.6M',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-23 10:20:57',
				'created_at' => '2014-10-23 10:20:57',
				'deleted_at' => NULL,
			),
			84 => 
			array (
				'id' => 91,
				'main_contact_id' => NULL,
				'address_id' => 431,
				'name' => 'PABELLON FERIAL CIUDAD REAL',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'PABELLON EXPOSICIONES',
				'capacity' => '10000',
				'dimension_height' => '12M',
				'dimension_width' => '48M',
				'dimension_length' => '107M',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-23 10:37:23',
				'created_at' => '2014-10-23 10:37:23',
				'deleted_at' => NULL,
			),
			85 => 
			array (
				'id' => 92,
				'main_contact_id' => NULL,
				'address_id' => 436,
				'name' => 'THE SPORTS AND CONCERTS COMPLEX “OLYMPIISKII”',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'THE BIG ARENA',
				'capacity' => '25000',
				'dimension_height' => '24',
				'dimension_width' => '90',
				'dimension_length' => '126',
				'rigging_capacity' => '400KG PER POINT',
				'notes' => '',
				'updated_at' => '2014-10-23 10:48:00',
				'created_at' => '2014-10-23 10:48:00',
				'deleted_at' => NULL,
			),
			86 => 
			array (
				'id' => 93,
				'main_contact_id' => NULL,
				'address_id' => 439,
				'name' => 'CIUDAD DEL ROCK',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '30000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-23 10:57:28',
				'created_at' => '2014-10-23 10:57:28',
				'deleted_at' => NULL,
			),
			87 => 
			array (
				'id' => 94,
				'main_contact_id' => NULL,
				'address_id' => 443,
				'name' => 'ROMEXPO',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '10000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-23 11:18:31',
				'created_at' => '2014-10-23 11:08:23',
				'deleted_at' => '2014-10-23 11:18:31',
			),
			88 => 
			array (
				'id' => 95,
				'main_contact_id' => NULL,
				'address_id' => 447,
				'name' => 'DU ARENA',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'THE O1NE',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-23 11:13:48',
				'created_at' => '2014-10-23 11:13:48',
				'deleted_at' => NULL,
			),
			89 => 
			array (
				'id' => 96,
				'main_contact_id' => NULL,
				'address_id' => 452,
				'name' => 'SPORTPALEIS ANTWERP',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'SPORTPALEIS',
				'capacity' => '18000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => 'TOT 80T, 2,5 TON PER PUNT',
				'notes' => '',
				'updated_at' => '2014-10-23 11:21:43',
				'created_at' => '2014-10-23 11:21:43',
				'deleted_at' => NULL,
			),
			90 => 
			array (
				'id' => 97,
				'main_contact_id' => NULL,
				'address_id' => 457,
				'name' => 'ROMEXPO',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'ROMEXPO',
				'capacity' => '10000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-23 11:28:44',
				'created_at' => '2014-10-23 11:28:44',
				'deleted_at' => NULL,
			),
			91 => 
			array (
				'id' => 98,
				'main_contact_id' => NULL,
				'address_id' => 462,
				'name' => 'AAA',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => 'AAA',
				'capacity' => '4000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '200',
				'notes' => '',
				'updated_at' => '2014-10-24 11:36:29',
				'created_at' => '2014-10-24 07:21:57',
				'deleted_at' => '2014-10-24 11:36:29',
			),
			92 => 
			array (
				'id' => 99,
				'main_contact_id' => NULL,
				'address_id' => 467,
				'name' => 'Nova Arena Anhembi',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => 'Nova Arena anhembi',
				'capacity' => '15000',
				'dimension_height' => '140m',
				'dimension_width' => '40m',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-06 15:39:36',
				'created_at' => '2014-11-06 15:39:36',
				'deleted_at' => NULL,
			),
			93 => 
			array (
				'id' => 100,
				'main_contact_id' => NULL,
				'address_id' => 493,
				'name' => 'Gandaria City',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Skeeno Hall',
				'capacity' => '3000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-19 11:25:54',
				'created_at' => '2014-11-19 11:25:54',
				'deleted_at' => NULL,
			),
			94 => 
			array (
				'id' => 101,
				'main_contact_id' => NULL,
				'address_id' => 498,
				'name' => 'Fort Canning Park',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => 'The Green',
				'capacity' => '5000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-19 15:39:54',
				'created_at' => '2014-11-19 15:33:53',
				'deleted_at' => NULL,
			),
			95 => 
			array (
				'id' => 102,
				'main_contact_id' => NULL,
				'address_id' => 501,
				'name' => 'test',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-20 08:54:01',
				'created_at' => '2014-11-20 08:52:00',
				'deleted_at' => NULL,
			),
			96 => 
			array (
				'id' => 103,
				'main_contact_id' => NULL,
				'address_id' => 504,
				'name' => 'Supernova Arena',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-24 16:16:41',
				'created_at' => '2014-11-24 16:16:41',
				'deleted_at' => NULL,
			),
			97 => 
			array (
				'id' => 104,
				'main_contact_id' => NULL,
				'address_id' => 506,
				'name' => 'Mahalaxmi Racecourse',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => '',
				'capacity' => '8000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-24 16:32:24',
				'created_at' => '2014-11-24 16:32:24',
				'deleted_at' => NULL,
			),
			98 => 
			array (
				'id' => 105,
				'main_contact_id' => NULL,
				'address_id' => 509,
				'name' => '02 Brixton Academy',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Main room',
				'capacity' => '4300',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-24 16:55:36',
				'created_at' => '2014-11-24 16:55:36',
				'deleted_at' => NULL,
			),
			99 => 
			array (
				'id' => 106,
				'main_contact_id' => NULL,
				'address_id' => 512,
				'name' => 'Belville Velodrome',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-11-28 10:25:35',
				'created_at' => '2014-11-28 10:25:35',
				'deleted_at' => NULL,
			),
			100 => 
			array (
				'id' => 107,
				'main_contact_id' => NULL,
				'address_id' => 519,
				'name' => 'Life Park',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => '',
				'capacity' => '10000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
			'notes' => 'Werkte slecht mee, nooduitgangen een probleem hier, stuk uit het hek laten zagen. Slechte verlichting. Eigenaar dacht moeilijk mee en wilde overal geld voor (wilde een deel opbrengst van de shuttlebus kaartjes, maar deze waren gratis, maar wilde hij alsnog geld). ',
				'updated_at' => '2014-12-01 16:16:34',
				'created_at' => '2014-12-01 16:16:34',
				'deleted_at' => NULL,
			),
			101 => 
			array (
				'id' => 108,
				'main_contact_id' => NULL,
				'address_id' => 520,
				'name' => ' KüçükÇiftlik Park',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => '',
				'capacity' => '15000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-01 16:20:00',
				'created_at' => '2014-12-01 16:17:40',
				'deleted_at' => NULL,
			),
			102 => 
			array (
				'id' => 109,
				'main_contact_id' => NULL,
				'address_id' => 523,
				'name' => 'Wild Waters',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'World Trade Center',
				'capacity' => '746',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-10 15:25:59',
				'created_at' => '2014-12-10 15:25:59',
				'deleted_at' => NULL,
			),
			103 => 
			array (
				'id' => 110,
				'main_contact_id' => NULL,
				'address_id' => 524,
				'name' => 'Wild Waters',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Main Floor',
				'capacity' => '10000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-10 15:36:41',
				'created_at' => '2014-12-10 15:36:41',
				'deleted_at' => NULL,
			),
			104 => 
			array (
				'id' => 111,
				'main_contact_id' => NULL,
				'address_id' => 529,
				'name' => 'MEO Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '18000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-10 15:54:47',
				'created_at' => '2014-12-10 15:54:47',
				'deleted_at' => NULL,
			),
			105 => 
			array (
				'id' => 112,
				'main_contact_id' => NULL,
				'address_id' => 532,
				'name' => 'Ziggo Dome',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Ziggo Dome',
				'capacity' => '17000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-16 16:24:08',
				'created_at' => '2014-12-16 16:24:08',
				'deleted_at' => NULL,
			),
			106 => 
			array (
				'id' => 113,
				'main_contact_id' => NULL,
				'address_id' => 536,
				'name' => 'Trade Fairs Center',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Bitan 1',
				'capacity' => '5000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-16 16:32:08',
				'created_at' => '2014-12-16 16:32:08',
				'deleted_at' => NULL,
			),
			107 => 
			array (
				'id' => 114,
				'main_contact_id' => NULL,
				'address_id' => 538,
				'name' => 'Zenith',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Zenith',
				'capacity' => '9000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-16 16:37:28',
				'created_at' => '2014-12-16 16:37:28',
				'deleted_at' => NULL,
			),
			108 => 
			array (
				'id' => 115,
				'main_contact_id' => NULL,
				'address_id' => 540,
				'name' => 'Tap 1',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Tap 1',
				'capacity' => '6000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-16 16:45:17',
				'created_at' => '2014-12-16 16:44:43',
				'deleted_at' => NULL,
			),
			109 => 
			array (
				'id' => 116,
				'main_contact_id' => NULL,
				'address_id' => 544,
				'name' => 'Globe',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Globe',
				'capacity' => '13850',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-16 16:50:19',
				'created_at' => '2014-12-16 16:50:19',
				'deleted_at' => NULL,
			),
			110 => 
			array (
				'id' => 117,
				'main_contact_id' => NULL,
				'address_id' => 545,
				'name' => 'Estadio de Ejercicio',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-16 16:53:09',
				'created_at' => '2014-12-16 16:53:09',
				'deleted_at' => NULL,
			),
			111 => 
			array (
				'id' => 118,
				'main_contact_id' => NULL,
				'address_id' => 548,
				'name' => 'Festhalle',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Festhalle',
				'capacity' => '15000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 10:37:10',
				'created_at' => '2014-12-17 10:37:10',
				'deleted_at' => NULL,
			),
			112 => 
			array (
				'id' => 119,
				'main_contact_id' => NULL,
				'address_id' => 549,
				'name' => 'Mitsubishi Electric Halle',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Mitsubishi Electric Halle',
				'capacity' => '7500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 10:42:52',
				'created_at' => '2014-12-17 10:42:52',
				'deleted_at' => NULL,
			),
			113 => 
			array (
				'id' => 120,
				'main_contact_id' => NULL,
				'address_id' => 550,
				'name' => 'Palau Sant Jordi',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Palau Sant Jordi',
				'capacity' => '24000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:14:04',
				'created_at' => '2014-12-17 10:46:11',
				'deleted_at' => '2014-12-17 14:14:04',
			),
			114 => 
			array (
				'id' => 121,
				'main_contact_id' => NULL,
				'address_id' => 551,
				'name' => 'Fiera',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 10:48:42',
				'created_at' => '2014-12-17 10:48:42',
				'deleted_at' => NULL,
			),
			115 => 
			array (
				'id' => 122,
				'main_contact_id' => NULL,
				'address_id' => 552,
				'name' => 'Hydro Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Hydro Arena',
				'capacity' => '13000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 11:07:47',
				'created_at' => '2014-12-17 11:07:47',
				'deleted_at' => NULL,
			),
			116 => 
			array (
				'id' => 123,
				'main_contact_id' => NULL,
				'address_id' => 553,
				'name' => 'Phones 4u Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Phones 4u Arena',
				'capacity' => '21000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 11:48:26',
				'created_at' => '2014-12-17 11:48:26',
				'deleted_at' => NULL,
			),
			117 => 
			array (
				'id' => 124,
				'main_contact_id' => NULL,
				'address_id' => 554,
				'name' => 'Alexandra Palace',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Alexandra Palace',
				'capacity' => '10000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 11:51:38',
				'created_at' => '2014-12-17 11:51:38',
				'deleted_at' => NULL,
			),
			118 => 
			array (
				'id' => 125,
				'main_contact_id' => NULL,
				'address_id' => 555,
				'name' => 'Earls Court',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Earls Court',
				'capacity' => '20000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 11:54:42',
				'created_at' => '2014-12-17 11:54:42',
				'deleted_at' => NULL,
			),
			119 => 
			array (
				'id' => 126,
				'main_contact_id' => NULL,
				'address_id' => 556,
				'name' => 'Montpellier Events',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => 'Exhibition Centre',
				'capacity' => '20000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'Mogelijke locatie voor ASOT? Locatie van I Love Techno France 2014.',
				'updated_at' => '2014-12-17 12:06:08',
				'created_at' => '2014-12-17 12:06:08',
				'deleted_at' => NULL,
			),
			120 => 
			array (
				'id' => 127,
				'main_contact_id' => NULL,
				'address_id' => 557,
				'name' => 'Friends Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '40000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'Capacity is 65000 - Swedish House Maffia\'s Until now tour',
				'updated_at' => '2014-12-17 13:41:21',
				'created_at' => '2014-12-17 13:41:21',
				'deleted_at' => NULL,
			),
			121 => 
			array (
				'id' => 128,
				'main_contact_id' => NULL,
				'address_id' => 558,
				'name' => 'Forum',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '18500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'capacity 10,000 guests standing, 8500 seated - Swedish House Mafia their Until now tour',
				'updated_at' => '2014-12-17 13:45:29',
				'created_at' => '2014-12-17 13:45:29',
				'deleted_at' => NULL,
			),
			122 => 
			array (
				'id' => 129,
				'main_contact_id' => NULL,
				'address_id' => 559,
				'name' => 'O2 Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '20000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'Swedish House Mafia with their Until Now tour',
				'updated_at' => '2014-12-17 13:59:04',
				'created_at' => '2014-12-17 13:59:04',
				'deleted_at' => NULL,
			),
			123 => 
			array (
				'id' => 130,
				'main_contact_id' => NULL,
				'address_id' => 560,
				'name' => 'WM Park Planai',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'Capacity unknown - Swedish House Mafia tour Until Now',
				'updated_at' => '2014-12-17 14:00:28',
				'created_at' => '2014-12-17 14:00:28',
				'deleted_at' => NULL,
			),
			124 => 
			array (
				'id' => 131,
				'main_contact_id' => NULL,
				'address_id' => 561,
				'name' => 'Brixton Academy',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '4000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:02:56',
				'created_at' => '2014-12-17 14:02:56',
				'deleted_at' => NULL,
			),
			125 => 
			array (
				'id' => 132,
				'main_contact_id' => NULL,
				'address_id' => 562,
				'name' => 'Victoria Warehouse',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '4500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:03:25',
				'created_at' => '2014-12-17 14:03:25',
				'deleted_at' => NULL,
			),
			126 => 
			array (
				'id' => 133,
				'main_contact_id' => NULL,
				'address_id' => 563,
				'name' => 'The Arches',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '2000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:04:20',
				'created_at' => '2014-12-17 14:04:20',
				'deleted_at' => NULL,
			),
			127 => 
			array (
				'id' => 134,
				'main_contact_id' => NULL,
				'address_id' => 564,
				'name' => 'Geneve Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '9500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:04:49',
				'created_at' => '2014-12-17 14:04:49',
				'deleted_at' => NULL,
			),
			128 => 
			array (
				'id' => 135,
				'main_contact_id' => NULL,
				'address_id' => 565,
				'name' => 'Dock des Suds',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '3000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'Capacity is 2800',
				'updated_at' => '2014-12-17 14:05:39',
				'created_at' => '2014-12-17 14:05:39',
				'deleted_at' => NULL,
			),
			129 => 
			array (
				'id' => 136,
				'main_contact_id' => NULL,
				'address_id' => 566,
				'name' => 'Paulau Sant Jordi',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '8000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:06:52',
				'created_at' => '2014-12-17 14:06:52',
				'deleted_at' => NULL,
			),
			130 => 
			array (
				'id' => 137,
				'main_contact_id' => NULL,
				'address_id' => 567,
				'name' => 'Fabrik',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '5000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:07:23',
				'created_at' => '2014-12-17 14:07:23',
				'deleted_at' => NULL,
			),
			131 => 
			array (
				'id' => 138,
				'main_contact_id' => NULL,
				'address_id' => 568,
				'name' => 'Zenith',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '5000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:17:57',
				'created_at' => '2014-12-17 14:08:23',
				'deleted_at' => '2014-12-17 14:17:57',
			),
			132 => 
			array (
				'id' => 139,
				'main_contact_id' => NULL,
				'address_id' => 569,
				'name' => 'Ancienne Belgique',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '2000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:08:55',
				'created_at' => '2014-12-17 14:08:55',
				'deleted_at' => NULL,
			),
			133 => 
			array (
				'id' => 140,
				'main_contact_id' => NULL,
				'address_id' => 570,
				'name' => 'Gashouder',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '3500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:09:30',
				'created_at' => '2014-12-17 14:09:30',
				'deleted_at' => NULL,
			),
			134 => 
			array (
				'id' => 141,
				'main_contact_id' => NULL,
				'address_id' => 571,
				'name' => 'Columbia Halle',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '3500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:10:20',
				'created_at' => '2014-12-17 14:10:20',
				'deleted_at' => NULL,
			),
			135 => 
			array (
				'id' => 142,
				'main_contact_id' => NULL,
				'address_id' => 572,
				'name' => 'Tap 1',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '5000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:17:40',
				'created_at' => '2014-12-17 14:12:59',
				'deleted_at' => '2014-12-17 14:17:40',
			),
			136 => 
			array (
				'id' => 143,
				'main_contact_id' => NULL,
				'address_id' => 573,
				'name' => 'Atlantico',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '4000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:14:33',
				'created_at' => '2014-12-17 14:14:33',
				'deleted_at' => NULL,
			),
			137 => 
			array (
				'id' => 144,
				'main_contact_id' => NULL,
				'address_id' => 574,
				'name' => 'Fabrique',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '2950',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:15:11',
				'created_at' => '2014-12-17 14:15:11',
				'deleted_at' => NULL,
			),
			138 => 
			array (
				'id' => 145,
				'main_contact_id' => NULL,
				'address_id' => 575,
				'name' => 'Spektrum',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '10500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:16:14',
				'created_at' => '2014-12-17 14:16:14',
				'deleted_at' => NULL,
			),
			139 => 
			array (
				'id' => 146,
				'main_contact_id' => NULL,
				'address_id' => 579,
				'name' => 'Odyssey Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '12000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 14:42:47',
				'created_at' => '2014-12-17 14:42:47',
				'deleted_at' => NULL,
			),
			140 => 
			array (
				'id' => 147,
				'main_contact_id' => NULL,
				'address_id' => 582,
				'name' => 'The O2 Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '14000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-12-17 15:32:24',
				'created_at' => '2014-12-17 15:32:24',
				'deleted_at' => NULL,
			),
			141 => 
			array (
				'id' => 148,
				'main_contact_id' => NULL,
				'address_id' => 590,
				'name' => 'Mount Smart Stadium',
				'indoor_or_outdoor' => '1',
				'name_of_hall' => '',
				'capacity' => '40000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'Avicci tour - capacity 47000 ',
				'updated_at' => '2015-01-05 10:37:51',
				'created_at' => '2015-01-05 10:37:51',
				'deleted_at' => NULL,
			),
			142 => 
			array (
				'id' => 149,
				'main_contact_id' => NULL,
				'address_id' => 591,
				'name' => 'Hakkasan',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '7000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-01-05 10:49:05',
				'created_at' => '2015-01-05 10:49:05',
				'deleted_at' => NULL,
			),
			143 => 
			array (
				'id' => 150,
				'main_contact_id' => NULL,
				'address_id' => 592,
				'name' => 'Cocorico',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '2500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '0',
				'notes' => 'Tour Afrojack',
				'updated_at' => '2015-01-05 10:56:45',
				'created_at' => '2015-01-05 10:56:35',
				'deleted_at' => NULL,
			),
			144 => 
			array (
				'id' => 151,
				'main_contact_id' => NULL,
				'address_id' => 593,
				'name' => 'Anhembi',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '40000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'capactity 50000+',
				'updated_at' => '2015-01-08 12:06:51',
				'created_at' => '2015-01-08 12:06:51',
				'deleted_at' => NULL,
			),
			145 => 
			array (
				'id' => 152,
				'main_contact_id' => NULL,
				'address_id' => 594,
				'name' => 'Rio Centro',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '4500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-01-08 12:13:25',
				'created_at' => '2015-01-08 12:13:25',
				'deleted_at' => NULL,
			),
			146 => 
			array (
				'id' => 153,
				'main_contact_id' => NULL,
				'address_id' => 595,
				'name' => 'O2 World ',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '16000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-01-08 12:17:03',
				'created_at' => '2015-01-08 12:17:03',
				'deleted_at' => NULL,
			),
			147 => 
			array (
				'id' => 154,
				'main_contact_id' => NULL,
				'address_id' => 596,
				'name' => 'Palais Omnisport de Bercy',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '16065',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-01-08 12:19:18',
				'created_at' => '2015-01-08 12:19:18',
				'deleted_at' => NULL,
			),
			148 => 
			array (
				'id' => 155,
				'main_contact_id' => NULL,
				'address_id' => 597,
				'name' => 'Muzik',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '3000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-01-08 12:37:34',
				'created_at' => '2015-01-08 12:37:34',
				'deleted_at' => NULL,
			),
			149 => 
			array (
				'id' => 156,
				'main_contact_id' => NULL,
				'address_id' => 598,
				'name' => 'Pacha',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '2000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-01-08 12:50:23',
				'created_at' => '2015-01-08 12:50:23',
				'deleted_at' => NULL,
			),
			150 => 
			array (
				'id' => 157,
				'main_contact_id' => NULL,
				'address_id' => 599,
				'name' => 'Allianz Stadium',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '40000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'Capacity is 45500',
				'updated_at' => '2015-01-08 13:33:15',
				'created_at' => '2015-01-08 13:33:15',
				'deleted_at' => NULL,
			),
			151 => 
			array (
				'id' => 158,
				'main_contact_id' => NULL,
				'address_id' => 600,
				'name' => 'Saitama Super Arena',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '37000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-01-08 13:37:14',
				'created_at' => '2015-01-08 13:37:14',
				'deleted_at' => NULL,
			),
			152 => 
			array (
				'id' => 159,
				'main_contact_id' => NULL,
				'address_id' => 601,
				'name' => 'FNB Stadium',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '40000',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => 'Capacity 94736',
				'updated_at' => '2015-01-08 13:40:30',
				'created_at' => '2015-01-08 13:40:30',
				'deleted_at' => NULL,
			),
			153 => 
			array (
				'id' => 257,
				'main_contact_id' => NULL,
				'address_id' => 289,
				'name' => 'test',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2014-10-22 11:48:51',
				'created_at' => '2014-10-02 11:08:48',
				'deleted_at' => '2014-10-22 11:48:51',
			),
			154 => 
			array (
				'id' => 411,
				'main_contact_id' => NULL,
				'address_id' => 603,
				'name' => 'zzzzzz',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '1',
				'dimension_width' => '1',
				'dimension_length' => '1',
				'rigging_capacity' => '160',
				'notes' => '',
				'updated_at' => '2015-03-16 13:48:52',
				'created_at' => '2015-03-16 13:48:52',
				'deleted_at' => NULL,
			),
			155 => 
			array (
				'id' => 412,
				'main_contact_id' => NULL,
				'address_id' => 604,
				'name' => 'yyy',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '2',
				'dimension_width' => '2',
				'dimension_length' => '2',
				'rigging_capacity' => '320',
				'notes' => '',
				'updated_at' => '2015-03-16 13:50:21',
				'created_at' => '2015-03-16 13:50:21',
				'deleted_at' => NULL,
			),
			156 => 
			array (
				'id' => 413,
				'main_contact_id' => NULL,
				'address_id' => 605,
				'name' => 'zxy',
				'indoor_or_outdoor' => '0',
				'name_of_hall' => '',
				'capacity' => '500',
				'dimension_height' => '',
				'dimension_width' => '',
				'dimension_length' => '',
				'rigging_capacity' => '',
				'notes' => '',
				'updated_at' => '2015-03-16 15:14:38',
				'created_at' => '2015-03-16 15:14:38',
				'deleted_at' => NULL,
			),
		));
	}

}
